name: Build and Deploy Nuxt3 Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt3 project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuxt3-build
          path: dist
